# fly.toml app configuration file generated for lnurlnwc on 2025-01-23T00:34:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lnurlnwc'
primary_region = 'fra'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '1m0s'
    timeout = '5s'
    grace_period = '45s'
    method = 'GET'
    path = '/ping'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
